language: nix
script:
- nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/1d4de0d552ae9aa66a5b8dee5fb0650a4372d148
- echo "trusted-users = root ${USER}" | sudo tee -a /etc/nix/nix.conf || true
- sudo pkill nix-daemon || true
- cachix use free-algebras
- nix-build -A heyting-algebras --argstr compiler $COMPILER
- cachix push free-algebras ./result
matrix:
  include:
  - name: ghc863
    env: COMPILER="ghc863"
  - name: ghc844
    env: COMPILER="ghc844"
  - name: ghc822
    env: COMPILER="ghc822"
  - name: ghc802
    env: COMPILER="ghc802"
  - name: ghc863
    env: COMPILER="ghc863"
    os: osx
env:
  global:
    secure: VXTOr94llPu1FWJmr1hkJIRGxzOhit0sZBj5a8ovLbQLDK2x82H30Y7Q0FEbOirIv+llLNwSRcJjKxGO2sNNdZprc3J7YGtNTO4ailhs1qVm+FuIRqLpZ1yPzEam03GXfJamyNUGAx3NZFJnh6vGwzEu8EHVbo4qHlTMpRWJCZ9turn/+DIvqwct6h1ahrKsoYNjce1KgJn3sQ9qYxDKWjZWJvhyT1XxNCf8wlaioHMYXpZxqauo1XnSnXF+ojoC5WTsBBx60lMcBJ/jtguZtgxbe+veYeI4Td8t/pBT2GgLWDsDiiAbZ6M6ZMcwRd2mDxYmSs5jBcJ4kcB+J/sZuzsS4qaujtuRPD6EuwsH12B120EkqK/dWLl0t/8d/VlPTUp9lz0aMPcjlSwlMtNpZl+gWp34AfyDMfmbWPXiOutIB04D6AZ0j+yNSxcmeUad4oZOxSetEHQIeBXnWn/cDwq40kb8HV4MFXXZPicFWY3KWhx7fNYhmuHvs9DmwtRZ2EYvUmjcfnjP9+XG2oERRlbcsI8rOdjUH3+SXLT9yraCnqiw4jFrDTfJN2oe1xxPV9OL0zLjINwvpuXFYstqNZEKl34ZyWd+6W2zjbem6X/e3mjHN5Ueca9epJ+8WPjdbhTnWt8uhuiQA8gPDi+GNUqO1401kRm/HY3G3COhAPE=
