language: nix
script: nix-build -A heyting-algebras --argstr compiler $COMPILER
matrix:
  include:
    - name: "ghc843"
      env: COMPILER="ghc843"
    - name: "ghc822"
      env: COMPILER="ghc822"
    - name: "ghc802"
      env: COMPILER="ghc802"

