language: nix
script:
  - nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/1d4de0d552ae9aa66a5b8dee5fb0650a4372d148
  - cachix use heyting-algebras
  - nix-build -A heyting-algebras --argstr compiler $COMPILER
matrix:
  include:
    - name: "ghc843"
      env: COMPILER="ghc843"
    - name: "ghc822"
      env: COMPILER="ghc822"
    - name: "ghc802"
      env: COMPILER="ghc802"
