name: "POSIX"
on: [push]

jobs:
  tests:
    name: "heyting-algebras"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://hydra.iohk.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - name: "cachix"
        uses: cachix/cachix-action@v8
        with:
          name: "heyting-algebras"
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken:  '${{ secrets.CACHIX_AUTH_TOKEN  }}'

      - name: "nix"
        run: |
            echo 'substituters = https://hydra.iohk.io/' | sudo tee -a /etc/nix/nix.conf
            echo 'trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=' | sudo tee -a /etc/nix/nix.conf

      - name: "cachix iohk"
        run: cachix use iohk

      - name: "[GHC 8.6.5]  heyting-algebras"
        run: |
          nix-build default.nix --argstr compiler ghc865 -A heyting-algebras

      - name: "[GHC 8.8.4]  heyting-algebras"
        run: nix-build default.nix --argstr compiler ghc884 -A heyting-algebras

      - name: "[GHC 8.10.4] heyting-algebras"
        run: nix-build default.nix --argstr compiler ghc8104 -A heyting-algebras
